### ISSUE TITLE
Run tests on all supported platforms and Python versions

### ISSUE THREAD

**Issue by cbenhagen** [ascmitc/mhl#77]
Adding a test matrix which runs unit and integration tests on all supported platforms and Python versions will help us catch issues early.

**Comment by jwaggs** [comment]
@cbenhagen you use Tox for this?

**Comment by cbenhagen** [comment]
Maybe we just use the matrix feature of GitHub? Something along the line of:

```yaml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, 3.10, pypy3]
```
